#!/bin/bash

COMPILER_DIR=@COMPILER_DIR@
COMPILER_BINDIR=${COMPILER_DIR}/bin
BIN_NAME=$(basename ${0})
# Fix for stlinux24
BIN_NAME=${BIN_NAME/"sh4-stlinux24-linux-gnu"/"sh4-linux"}
#BIN_NAME=${BIN_NAME/stlinux24}
#BIN_NAME=${BIN_NAME/gnu}

${COMPILER_BINDIR}/${BIN_NAME} "$@"

